name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Congratulations! You've made your first issue to art. We will respond your issue and do our best to solve it as soon as possible, you can see more issues https://github.com/sepandhaghighi/art/issues.'
        pr-message: 'Congratulations! You've made your first Pull request to art.Changes and improvements are more than welcome! heart Feel free to fork and open a pull request. Contribution Guidline :(https://github.com/sepandhaghighi/art/blob/master/.github/CONTRIBUTING.md)'
